
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://adityac94.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Aditya Chattopadhyay"
title: "Aditya Chattopadhyay - ML Enthusiast"
description: "My personal webpage :)"
keywords: "aditya, chattopadhyay, machine learning, deep learning, optimization methods"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "/img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "I have no special talents. I am only passionately curious. ~ <i>Albert Einstein</i>" 
  - text: "Simplicity is the ultimate sophistication. ~ <i>Leonardo Da Vinci</i>"

me-img: "/img/author.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

#me-img: "https://github.com/adityac94.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/author.jpg"
    date: "A New Chapter"
    description: "~ To gain more exposure to core Machine Learning research, I decided to join the Deep Learing lab of Prof. Vineeth N Balasubramanian, at the Indian Institute of Technology (IIT), Hyderabad. <br/> 
	~ Here, I worked on making these deep learning algorithms more <i>interpretable</i>. This is especially important in risk-critical tasks like Healthcare systems, self-driving cars etc. If we know why the machine does what it does, it would be much easier to have faith in it! <br />
	~ Our paper on explainability in CNNs using gradient information will appear in the <b>IEEE Winter Conference on Applications of Computer Vision (WACV2018)</b> in the algorithms track. <br />
	~ Learnt a lot about optimization methods from Prof. Vineeth, by attending his course on <i> Convex Optimization in Machine Learning </i> at IIT-H."



  - image: "/img/timeline/author.jpg"
    date: "Thesis Topic Conundrum"
    description: "~ With a burgeoning interest in machine learning and probability, I chose <u><b>probabilistic modelling of molecular system trajectories</b></u> as the focus of my Master's thesis. <br/>
	~ Often molecular trajectories are analysed using Markov Chains, which reveal patterns on time-scales much larger than the length of a typical simulation time. However, such methods are limited by a necessity of explicit integration of Newton's equations of motion to generate the trajectory. <br />
	~ More efficient sampling techniques exist (variants of Monte-Carlo methods) but these methods lack temporal ordering of trajectory snapshots, precluding the possibility of constructing a transition matrix, which is core to all Markov Chain based methods. <br />
	~ In my thesis, I try to address this problem by using <i> Expectation Maximization </i> on a hybrid gaussian-boltzman probability density function to learn these temporal dependencies from Monte Carlo simulation data. <br />"

  - image: "/img/timeline/author.jpg"
    date: "Fledgling Researcher"
    description: "~ Selected for a summer research internship at the Centre of Multiscale Theory and 
Computation, University of Munster in the lab of Prof. Mark Waller. Formulated a project involving machine 
learning to discern chemical structures from their infra-red spectra. <br/>
	~ Worked in the lab of Prof. U Deva Priyakumar where we tried to understand the mysteries behind protein unfolding using <i>in-silico</i> methods. We discovered a novel mode of interaction through which urea molecules denature proteins which brings us a tiny step closer to solving the puzzle in the grand scheme of things! This work is published in [JACS - 2017](pubs.acs.org/doi/abs/10.1021/jacs.7b05463) <br />
	~ Consistently in Dean's List every semester since Aug '15, which is awarded to the top 15% students in a batch."	

  - image: "/img/timeline/author.jpg"
    date: "Novice Hacker"
    description: "~ Qualified for ACM-ICPC Asia Regionals (Amritapuri). <br/>
~ Developed a [SQL engine](https://bitbucket.org/adityababiblue1994/mini-dbms) to select, insert, delete and join records in a relational database. Implemented external merge-sort to quickly sort through the records.
sorting of records using external-merge sort.  <br/>
~ Developed a web-app to simultaneously edit or view documents on a cloud server without having to download the 
files. Implemented a [REST-API](https://github.com/adityac94/Cloud_Docspad). <br/>
~ Inspired from the Japanese Anime, Beyblade, developed a 3D [spinning top game](https://drive.google.com/file/d/0BzS5KZjihEdybjlfY3pXRTJ2aFk/view?usp=sharing) with multiplayer facility in Unity."

  - image: "/img/timeline/author.jpg"
    date: "Humble Beginnings..."
    description: "~ Embarked on a five year long journey for a dual degree programme at the International 
Institute of Information Technology (IIIT), Hyderabad [B.Tech in Computer Science & MS in Computational Natural 
Sciences]. "


# First image of the Timeline

timeline-img: "/img/timeline/author.jpg"

###########
# Contact #
###########

email: "aditya[dot]c[at]research[dot]iiit[dot]ac[dot]in"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/adityachattopadhyay.5"
  - title: "bitbucket"
    url: "https://bitbucket.com/adityababiblue1994"
  - title: "github"
    url: "https://github.com/adityac94"
 # - title: "bitcoin"
 #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
 # - title: "rss"
 #   url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  CV: 'cv'
  Publications: 'publications'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
