
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://adityac94.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Aditya Chattopadhyay"
title: "Aditya Chattopadhyay - ML Enthusiast"
description: "My personal webpage :)"
keywords: "aditya, chattopadhyay, machine learning, deep learning, optimization methods"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "/img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "I have no special talents. I am only passionately curious. ~ <i>Albert Einstein</i>" 
  - text: "Simplicity is the ultimate sophistication. ~ <i>Leonardo Da Vinci</i>"

me-img: "/img/author.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

#me-img: "https://github.com/adityac94.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/back_img_net.jpg"
    date: "June 2017 - Present"
    description: "Beside working on a cool data structures for [*pufferfish*](https://github.com/COMBINE-lab/pufferfish), de-Bruijn graph 
based mappers, I got really interested in publicly available big data. With Rob, I am now figuring out this maze of 
[Sequence Read Archive](https://www.ncbi.nlm.nih.gov/sra), and trying to find meaningful insights from this exponentially increasing public database. 
Keep checking for exciting upcoming news. Released [[biorXiv]](https://doi.org/10.1101/191874)."


  - image: "/img/back_img_net.jpg"
    date: "March 2017 - May 2017"
    description: "We worked on a new way for solving the abundance calculation problem for RNA-seq read mapping. 
    Kallisto and RapMap are not as accurate as you think in special cases, such as discussed
    [here](https://cgatoxford.wordpress.com/2016/08/17/why-you-should-stop-using-featurecounts-htseq-or-cufflinks2-and-start-using-kallisto-salmon-or-sailfish/).
    We propose Selective Alignment. Preprinted [[biorXiv]](https://doi.org/10.1101/138800)."

  - image: "/img/back_img_net.jpg"
    date: "Oct 2016 - Feb 2017"
    description: "We worked on RNA-seq compression algorithm. Developed a state-of-the-art RNA-seq compression tool,
    introducing the idea of semi-reference based compression, now published in [*Bioinformatics*](https://doi.org/10.1093/bioinformatics/btx428) now. I also worked on a poster 
    with [Prof Siepel](http://siepellab.labsites.cshl.edu/), presented in [*BioData*](https://meetings.cshl.edu/meetings.aspx?meet=DATA&year=16)."

  - image: "/img/back_img_net.jpg"
    date: "Aug '15 - Aug '16"
    description: "~ Worked in the lab of Prof. U Deva Priyakumar where we tried to understand the mysteries behind protein unfolding using <i>in-silico</i> methods. We discovered a novel mode of interaction through which urea molecules denature proteins which brings us a tiny step closer to solving the puzzle in the grand scheme of things! This work is published in [JACS - 2017](pubs.acs.org/doi/abs/10.1021/jacs.7b05463) <br />
~ Consistently in Dean's List every semester since Aug '15, which is awarded to the top 15% students in a batch."

  - image: "/img/timeline/author.jpg"
    date: "Aug '14 - Aug '15"
    description: "~ Selected for a 2 month research internship at the Centre of Multiscale Theory and 
Computation, University of Munster in the lab of Prof. Mark Waller. Formulated a project involving machine 
learning to discern chemical structures from their infra-red spectra. <br/>
		~ Inspired from the Japanese Anime, Beyblade, developed a 3D spinning top game with multiplayer facility in [Unity](https://drive.google.com/file/d/0BzS5KZjihEdybjlfY3pXRTJ2aFk/view?usp=sharing)."

  - image: "/img/timeline/author.jpg"
    date: "Aug '12 - Aug' 14"
    description: "~ Qualified for ACM-ICPC Asia Regionals (Amritapuri). <br/>
~ Developed a [SQL engine](https://bitbucket.org/adityababiblue1994/mini-dbms) to select, insert, delete and 
sorting of records using external-merge sort.  <br/>
~ Developed a web-app to simultaneously edit or view documents on a cloud server without having to download the 
files. Implemented a [REST-API](https://github.com/adityac94/Cloud_Docspad)."

  - image: "/img/timeline/author.jpg"
    date: "Aug '12"
    description: "Embarked on a five year long journey for a dual degree programme at the International 
Institute of Information Technology (IIIT), Hyderabad [B.Tech in Computer Science & MS in Computational Natural 
Sciences]. "


# First image of the Timeline

timeline-img: "/img/timeline/author.jpg"

###########
# Contact #
###########

email: "aditya[dot]c[at]research[dot]iiit[dot]ac[dot]in"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/adityachattopadhyay.5"
  - title: "bitbucket"
    url: "https://bitbucket.com/adityababiblue1994"
  - title: "github"
    url: "https://github.com/adityac94"
 # - title: "bitcoin"
 #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
 # - title: "rss"
 #   url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  CV: 'cv'
  Publications: 'publications'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
